### introduction to Heterogenous Graphs
this note book provide the details of the heterograph of the acm dataset that is discussed in the blog.

In [77]:
%matplotlib inline
import dgl
import numpy as np
import scipy.sparse as sp
# Creating from networkx graph
import networkx as nx
import scipy.io
import urllib.request


In [2]:
data_url = 'https://data.dgl.ai/dataset/ACM.mat'
data_file_path = 'ACM.mat'

urllib.request.urlretrieve(data_url, data_file_path)
data = scipy.io.loadmat(data_file_path)
print(list(data.keys()))

['__header__', '__version__', '__globals__', 'TvsP', 'PvsA', 'PvsV', 'AvsF', 'VvsC', 'PvsL', 'PvsC', 'A', 'C', 'F', 'L', 'P', 'T', 'V', 'PvsT', 'CNormPvsA', 'RNormPvsA', 'CNormPvsC', 'RNormPvsC', 'CNormPvsT', 'RNormPvsT', 'CNormPvsV', 'RNormPvsV', 'CNormVvsC', 'RNormVvsC', 'CNormAvsF', 'RNormAvsF', 'CNormPvsL', 'RNormPvsL', 'stopwords', 'nPvsT', 'nT', 'CNormnPvsT', 'RNormnPvsT', 'nnPvsT', 'nnT', 'CNormnnPvsT', 'RNormnnPvsT', 'PvsP', 'CNormPvsP', 'RNormPvsP']


In [78]:
G = dgl.heterograph({
        ('paper', 'written-by', 'author') : data['PvsA'],
        ('author', 'writing', 'paper') : data['PvsA'].transpose(),
        ('paper', 'citing', 'paper') : data['PvsP'],
        ('paper', 'cited', 'paper') : data['PvsP'].transpose(),
        ('paper', 'is-about', 'subject') : data['PvsL'],
        ('subject', 'has', 'paper') : data['PvsL'].transpose(),
    })
G

Graph(num_nodes={'author': 17431, 'paper': 12499, 'subject': 73},
      num_edges={('paper', 'written-by', 'author'): 37055, ('author', 'writing', 'paper'): 37055, ('paper', 'citing', 'paper'): 30789, ('paper', 'cited', 'paper'): 30789, ('paper', 'is-about', 'subject'): 12499, ('subject', 'has', 'paper'): 12499},
      metagraph=[('author', 'paper'), ('paper', 'author'), ('paper', 'paper'), ('paper', 'paper'), ('paper', 'subject'), ('subject', 'paper')])

In [11]:
G.ntypes

['author', 'paper', 'subject']

In [17]:
G.nodes('author')

tensor([    0,     1,     2,  ..., 17428, 17429, 17430])

In [112]:
def author(number):
    return data['A'][number][0][0]
def find_author_by_name(name):
    for i in range(17430):
        if author(i).find(name) >= 0:
            print(i, author(i))

In [113]:
find_author_by_name("Dongarra")

5100 Jack J. Dongarra


In [104]:
def institution(number):
    return data['F'][number][0][0]
def find_institution_by_name(name):
    for i in range(len(data['F'])):
        if institution(i).find(name) >= 0:
            print(i, institution(i))

In [115]:
def subject(number):
    return data['L'][number][0][0]

In [105]:
find_institution_by_name("Indiana")

231 Indiana University
232 Indiana University Purdue University Indianapolis


5100 Jack J. Dongarra


In [108]:
find_author_by_name("Wise")

6313 David S. Wise
9342 Charles Wiseman
11618 G. Bowden Wise


In [35]:
G['writing']

Graph(num_nodes={'author': 17431, 'paper': 12499},
      num_edges={('author', 'writing', 'paper'): 37055},
      metagraph=[('author', 'paper')])

In [57]:
G['writing'].out_edges(5100)

(tensor([5100]), tensor([9626]))

In [58]:
data['P'][9626]

array([array(["'Bi-objective scheduling algorithms for optimizing makespan and reliability on heterogeneous systems  We tackle the problem of scheduling task graphs onto a heterogeneous set of machines, where each processor has a probability of failure governed by an exponential law. The goal is to design algorithms that optimize both makespan and reliability. First, we provide an optimal scheduling algorithm for independent unitary tasks where the objective is to maximize the reliability subject to makespan minimization. For the bi-criteria case, we provide an algorithm that approximates the Pareto-curve. Next, for independent non-unitary tasks, we show that the product { failure rate }x { unitary instruction execution time } is crucial to distinguish processors in this context. Based on these results we are able to let the user choose a trade-off between reliability maximization and makespan minimization. For general task graphs we provide a method for converting scheduling heuristic

In [64]:
G['written-by'].out_edges(9626)

(tensor([9626, 9626, 9626, 9626]), tensor([ 1296,  5100,  8796, 10897]))

In [66]:
G['citing'].out_edges(9626)

(tensor([], dtype=torch.int64), tensor([], dtype=torch.int64))

In [76]:
[author(i) for i in G['written-by'].out_edges(9626)[1] ]

['Emmanuel Jeannot', 'Jack J. Dongarra', 'Zhiao Shi', 'Erik Saule']

In [117]:
[subject(i) for i in G['is-about'].out_edges(9626)[1] ]

['C.4']